name: Deploying react app to surge

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: egordm/gha-yarn-node-cache@v1
        
      - name: Install JS dependencies
        run: yarn install
        
      - name: Build React App
        run: yarn build

      - name: Install Surge
        run: npm install surge --global

      - name: Deploy to Surge
        run: surge ./build expense-tracker-ahmedfaraz.surge.sh --token ${{ secrets.SECRET_SURGE_TOKEN }}
